<title>Form Question</title>
<div class="form-question">
     <h2>Form Question</h2>
    <form action="<?= $block->escapeUrl($block->getUrl('*/*/confirm')) ?>" method="post">
          <div class="item-form">
              <label for="title">Title</label>
              <input type="text" name="title" id="title">
          </div>
            <div class="item-form">
                <label for="content">Content</label>
                <textarea class="content" name="content" id="content"></textarea>
            </div>
        <div class="button-confirm">
            <input class="button" type="submit" name="submit" value="Confirm">
        </div>

    </form>
</div>


