<?php
/** @var $block \Tigren\Testimonial\Block\Form */
?>
<a href="<?= $block->getUrl('*/*/') ?>">
    <button title="<?php echo __('Back') ?>" class="action default" id="custom_btn">
        <span><?php echo __('Back') ?></span>
    </button>
</a>
<form class="form"
      action="<?php echo $this->getUrl('*/*/save', ['_secure' => true]); ?>"
      enctype="multipart/form-data"
      id="custom-form"
      method="post"
      data-hasrequired="<?php echo __('* Required Fields') ?>"
      style="width:800px"
      data-mage-init='{"validation":{}}'>

    <fieldset class="fieldset">

        <h3 class="label"><span><?php echo __("Form Create Question") ?></span></h3><br />

        <div class="field name required">

            <label class="label" for="name"><span><?php echo __('Name') ?></span></label>

            <div class="control">

                <input name="name" id="name" title="<?php echo __('Name') ?>" class="input-text" type="text"
                       data-validate="{required:true}" />

            </div>

        </div>

        <div class="field email required">

            <label class="label" for="email"><span><?php echo __('Email') ?></span></label>

            <div class="control">

                <input name="email" id="email" title="<?php echo __('Email') ?>" class="input-text" type="email"
                       data-validate="{required:true, 'validate-email':true}" />

            </div>

        </div>
        <div class="field company required">

            <label class="label" for="company"><span><?php echo __('Company') ?></span></label>

            <div class="control">

                <input name="company" id="company" title="<?php echo __('Company') ?>" class="input-text" type="text"
                       data-validate="{required:true" />

            </div>

        </div>
        <div class="field rating required">

            <label class="label" for="rating"><span><?php echo __('Rating(star)') ?></span></label>

            <div class="control">

                <input name="rating" id="rating" title="<?php echo __('Rating(star)') ?>"
                       class="input-text validate-digits-range digits-range-1-5" type="text"
                       data-validate="{required:true,'validate-number':true}" />
                <i>Value is star from 1 to 5 star</i>
            </div>

        </div>
        <div class="field image">

            <label class="label" for="image"><span><?php echo __('Upload Image') ?></span></label>

            <div class="control">
                <input name="image" id="image" title="<?php echo __('Upload Image') ?>" class="input-file"
                       type="file" />
            </div>

        </div>

        <div class="field message required">

            <label class="label" for="message"><span><?php echo __('Message') ?></span></label>

            <div class="control">
                <textarea name="message" id="message" title="<?php echo __('Message') ?>" class="input-text" cols="5"
                          rows="3" data-validate="{required:true}"></textarea>

            </div>

        </div>

    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?php echo __('Submit') ?>" class="action submit primary" id="custom_btn">
                <span><?php echo __('Submit') ?></span>
            </button>
        </div>

    </div>

</form>

</div>
