<form class="form"
      action="<?php echo $this->getUrl('*/*/save', ['_secure' => true]); ?>"
      enctype="multipart/form-data"
      id="custom-form"
      method="post"
      data-hasrequired="<?php echo __('* Required Fields') ?>"

      data-mage-init='{"validation":{}}'>

    <fieldset class="fieldset">

        <h3 class="label"><span><?php echo __("Form Create Question") ?></span></h3><br />

        <div class="field name required">

            <label class="label" for="name"><span><?php echo __('Name') ?></span></label>

            <div class="control">

                <input name="name" id="name" title="<?php echo __('Name') ?>" class="input-text" type="text"
                       data-validate="{required:true}" />

            </div>

        </div>

        <div class="field email required">

            <label class="label" for="email"><span><?php echo __('Email') ?></span></label>

            <div class="control">

                <input name="email" id="email" title="<?php echo __('Email') ?>" class="input-text" type="email"
                       data-validate="{required:true, 'validate-email':true}" />

            </div>

        </div>

        <fieldset class="field required review-field-ratings">
            <div class="control">
                <div class="nested" id="product-review-table">
                    <?php for($i = 1;$i <= 5;$i++): ?>
                    <div class="field choice review-field-rating">
                        <label class="label" id=""><span><?= $block->escapeHtml(__(' Rating')) ?></span></label>
                        <div class="control review-control-vote">
                            <?php $iterator = 1; for($i = 1;$i <= 5;$i++): ?>
                                <input
                                    type="radio"
                                    name="ratings[]"
                                    id="<?='rating'.'_'.$i?>"
                                    value="<?=$i?>"
                                    class="radio"
                                    data-validate="{'rating-required':true}"
                                    aria-labelledby="" />
                                <label
                                    class="rating-<?= $block->escapeHtmlAttr($iterator) ?>"
                                    for="Rating_<?= $block->escapeHtmlAttr($iterator) ?>"
                                    title="<?= $block->escapeHtmlAttr(__('%1 %2', $iterator,
                                        $iterator > 1 ? __('stars') : __('star'))) ?>"
                                    id="Rating_<?=$iterator?>_label">
                                    <span><?= $block->escapeHtml(__('%1 %2', $iterator,
                                            $iterator > 1 ? __('stars') : __('star'))) ?></span>
                                </label>
                                <?php $iterator++; ?>
                            <?php endfor; ?>
                        </div>
                    </div>
                    <?php endfor; ?>
                </div>
                <input type="hidden" name="validate_rating" class="validate-rating" value="" />
            </div>
        </fieldset>
        <div class="field image">

            <label class="label" for="image"><span><?php echo __('Upload Image') ?></span></label>

            <div class="control">
                <input name="image" id="image" title="<?php echo __('Upload Image') ?>" class="input-file"
                       type="file" />
            </div>

        </div>

        <div class="field message required">

            <label class="label" for="message"><span><?php echo __('Message') ?></span></label>

            <div class="control">
                <textarea name="message" id="message" title="<?php echo __('Message') ?>" class="input-text" cols="5"
                          rows="3" data-validate="{required:true}"></textarea>

            </div>

        </div>

    </fieldset>

    <div class="actions-toolbar">

        <div class="primary">

            <input type="hidden" name="hideit" id="hideit" value="" />

            <button type="submit" title="<?php echo __('Submit') ?>" class="action submit primary" id="custom_btn">

                <span><?php echo __('Submit') ?></span>

            </button>

        </div>

    </div>

</form>

</div>
