<?php
/** @var $block Tigren\Testimonial\Block\Question */
?>
<a href="<?= $block->getUrl('*/*/create') ?>" class="btn primary stretched-link">
    <button class="action primary">
        Create Question
    </button>
</a>

<div class="table-wrapper">
    <h3>
        <span class="label label-default">Table Testimonial Question</span>
    </h3>
    <table class="data table" id="my-question-table">
        <caption class="table-caption"><?php echo __('Grid Record') ?></caption>
        <thead>
        <tr>
            <th scope="col" class="col count"><?php echo __('STT') ?></th>
            <th scope="col" class="col id"><?php echo __('ID') ?></th>
            <th scope="col" class="col name"><?php echo __('Name') ?></th>
            <th scope="col" class="col email"><?php echo __('Email') ?></th>
            <th scope="col" class="col email"><?php echo __('Company') ?></th>
            <th scope="col" class="col rating"><?php echo __('Rating') ?></th>
            <th scope="col" class="col image"><?php echo __('Image') ?></th>
            <th scope="col" class="col message"><?php echo __('Message') ?></th>
            <th scope="col" class="col createat"><?php echo __('Created At') ?></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <?php foreach ($block->getDataQuestion() as $key => $item): ?>
            <?php /** @var  Tigren\Testimonial\Model\Question $item */ ?>
            <td data-th="<?= $block->escapeHtml(__('STT')) ?>" class="col count">
                <?= $key + 1 ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('ID')) ?>" class="col id">
                <?= $item->getId() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Name')) ?>" class="col name">
                <?= $item->getName() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Email')) ?>" class="col email">
                <?= $item->getEmail() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Email')) ?>" class="col email">
                <?= $item->getCompany() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Rating')) ?>" class="col rating">
                <?php $start = '';
                for ($i = 1;
                     $i <= (int)$item->getRating();
                     $i++): ?>
                    <?php
                    $start = $start . '<span class="" style="color:#E3CC24">&#10030;</span>'
                    ?>
                <?php endfor; ?>
                <?= $start ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Image')) ?>" class="col image">
                <img style="width:50px;height: 50px"
                     src="<?= $block->getBaseUrl() . 'media/profile/image/' . $item->getProfileImage() ?>"
                     alt="profile_image" />
            </td>
            <td data-th="<?= $block->escapeHtml(__('Message')) ?>" class="col image">
                <?= $item->getMessage() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Created At')) ?>"
                class="col title">
                <?= $item->getCreatedAt() ?>
            </td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
