<?php
// @codingStandardsIgnoreFile
?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */
$priceHelper = $this->helper(\Tigren\CustomerGroupCatalog\Helper\Price::class);
$productId = $block->getSaleableItem()->getId();
//$currentProductId = $block->getRequest()->getParam('id');

/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
$rule = $priceHelper->getRuleMatch($block->getSaleableItem());
//(float)$priceDiscount = $block->getSaleableItem()->getTypeId() === 'simple'? $block->getSaleableItem()->getPriceInfo()->getPrice('final_price')->getValue() / 100 * $rule->getDiscountAmount():'';
?>
<?php if ($block->getSaleableItem()->getTypeId() === 'simple'): ?>
    <?php if ($block->hasSpecialPrice()): ?>
        <span class="special-price">
       <?php /* @escapeNotVerified */
       echo $block->renderAmount($finalPriceModel->getAmount(), [
           'display_label' => __('Special Price'),
           'price_id' => $block->getPriceId('product-price-' . $idSuffix),
           'price_type' => 'finalPrice',
           'include_container' => true,
           'schema' => $schema
       ]); ?>
   </span>
<!--    --><?php //else: ?>
<!--        <span class="price" style="text-decoration:line-through;color:steelblue">$--><?php ///* @escapeNotVerified */
//        echo $block->getSaleableItem()->getPriceInfo()->getPrice('final_price')->getValue() - $priceDiscount ?>
<!--        </span>-->
<!--        <b>Discount --><?php //= (int)$rule->getDiscountAmount() ?><!--%</b>-->
    <?php endif; ?>

    <?php if ($block->showMinimalPrice()): ?>
        <?php if ($block->getUseLinkForAsLowAs()): ?>
            <a href="<?= /* @escapeNotVerified */
            $block->getSaleableItem()->getProductUrl() ?>" class="minimal-price-link">
                <?= /* @escapeNotVerified */
                $block->renderAmountMinimal() ?>
            </a>
        <?php else: ?>
            <span class="minimal-price-link">
           <?= /* @escapeNotVerified */
           $block->renderAmountMinimal() ?>
       </span>
        <?php endif ?>
    <?php endif; ?>
<?php endif; ?>
